name: active_ecommerce_flutter
description: This is the flutter mobile application for active ecommerce cms

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  provider: ^4.3.2+2
  json_annotation: ^3.0.1
  logging: ^0.11.4
  connectivity: ^0.4.9+2
  shimmer: ^1.1.2
  bordered_text: ^1.0.0
  flutter_html: ^1.0.0
  flutter_svg: ^0.18.0
  url_launcher: ^5.5.2
  toast: ^0.1.5
  shared_preferences: ^0.5.6+3
  flutter_icons: ^1.1.0
  dotted_line: ^2.0.1
  timeline_list: ^0.0.3
  progress_dialog: ^1.2.4
  after_init: ^0.1.2
  webview_flutter: ^0.3.19+9
  clipboard: ^0.1.2+8
  google_fonts: ^1.1.1
  flutter_rating_bar: ^3.2.0+1
  expandable: ^4.1.4
  dropdown_search: ^0.4.8
  flutter_countdown_timer: ^2.1.0
  splashscreen: ^1.3.5
  package_info: ^0.4.3+2
  intl_phone_number_input: ^0.6.0
  flutter_chat_bubble: ^1.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  carousel_slider: ^2.3.1
  cached_network_image: ^2.2.0+1
  timeline_tile: ^1.0.0
  shared_value: ^0.4.0
  rename: ^1.3.0
  permission_handler: ^5.0.1+1
  image_picker: 0.6.7+22
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.5.9
  google_maps_place_picker: ^1.0.1
  firebase_messaging: ^7.0.3
  one_context: ^0.5.0
  social_share: ^2.0.4
  easy_localization: ^3.0.0-dev.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.6
  json_serializable: ^3.3.0
  flutter_launcher_icons: ^0.7.5
  google_maps_flutter: ^1.0.6

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lang/
    - dummy_assets/




  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
